sitebde_securite:
    resource: "@sitebdeSecuriteBundle/Resources/config/routing.yml"
    prefix:   /

sitebde_parrainage:
    resource: "@sitebdeParrainageBundle/Resources/config/routing.yml"
    prefix:   /


sitebde_site_vitrine:
    resource: "@sitebdeSiteVitrineBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

mentions_legales:
    path: /mentions_legales
    defaults: { _controller: AppBundle:Default:mentionsLegales }
    
envoyer_mail:
    path: /Envoi_mail
    defaults: { _controller: AppBundle:Default:envoyerMail }