# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html

security:

    firewalls:
        my_firewall:
            pattern:    ^/
            anonymous:  ~
            form_login:
                login_path: /login
                check_path: /login_check
            logout:
                path:   /logout
                target: /
    
    access_control:
        - { path: ^/admin , roles: ROLE_ADMIN }
        - { path: ^/parrainage, roles: [ROLE_ADMIN, ROLE_USER] }

    # providers:
    #     my_ldap:
    #         ldap:
    #             service: ldap
    #             base_dn: 
    #             search_dn: 
    #             search_password: 
    #             default_roles: ROLE_USER
    #             uid_key: uid


    providers:
        in_memory:
            memory:
                users:
                    etud: { password: 'etud' , roles: 'ROLE_USER' }
                    admin: { password: 'admin' , roles: 'ROLE_ADMIN' }
    
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        
# POUR FAIRE AVEC DU LDAP, C'EST EXPLIQUE LA
# http://symfony.com/doc/current/security/ldap.html