# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html

security:

    firewalls:
        my_firewall:
            pattern:    ^/
            anonymous:  ~
            # form_login:
            #     login_path: /connexion
            #     check_path: /verif-connexion
            # logout:
            #     path:   /deconnexion
            #     target: /
    
    # access_control:
    #     - { path: ^/admin , roles: ROLE_ADMIN }
    #     - { path: ^/parrainage, roles: [ROLE_ADMIN, ROLE_USER] }

    providers:
        in_memory:
            memory:
                users:
                    etud: { password: 'etud' , roles: ['ROLE_USER', 'ROLE_ADMIN'] }
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext








# security:

#     firewalls:
#         my_firewall:
#             pattern:    ^/
#             anonymous:  ~
#             form_login_ldap:
#                 login_path: /connexion
#                 check_path: /verif-connexion
#                 service:    ldap
#                 dn_string:  "uid={username},dc=univ-pau,dc=fr"
#             logout:
#                 path:   /deconnexion
#                 target: /
    
#     access_control:
#         - { path: ^/admin , roles: ROLE_ADMIN }
#         - { path: ^/parrainage, roles: [ROLE_ADMIN, ROLE_USER] }
    
#     providers:
#         my_ldap:
#             ldap:
#                 service:    ldap
#                 base_dn:    dc=univ-pau,dc=fr
#                 search_dn:  "uid=qlanusse,dc=univ-pau,dc=fr"
#                 search_password:    password
#                 default_roles:  ROLE_USER
#                 uid_key:    uid
                

# POUR FAIRE AVEC DU LDAP, C'EST EXPLIQUE LA
# http://symfony.com/doc/current/security/ldap.html