# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html

services:
    ldap:
        class: Symfony\Component\Ldap\LdapClient
        arguments:
            - kartxila.iutbayonne.univ-pau.fr   # host
            - null                              # port
            - 3                                 # version
            - false                             # SSL
            - true                              # TLS
