sitebde_parrainage_accueil:
    path:     /parrainage
    defaults: { _controller: sitebdeParrainageBundle:Parrainage:accueil }

sitebde_parrainage_premieres_annees:
    path:     /parrainage/premieres_annees
    defaults: { _controller: sitebdeParrainageBundle:Parrainage:listePremieresAnnees }

sitebde_parrainage_deuxiemes_annees:
    path:     /parrainage/deuxiemes_annees
    defaults: { _controller: sitebdeParrainageBundle:Parrainage:listeDeuxiemesAnnees }

sitebde_parrainage_details_profil:
    path:     /parrainage/details-{idEtudiant}
    defaults: { _controller: sitebdeParrainageBundle:Parrainage:detailsProfil }

sitebde_parrainage_profil:
    path:     /parrainage/profil
    defaults: { _controller: sitebdeParrainageBundle:Parrainage:profil }

sitebde_parrainage_profil_edition:
    path:     /parrainage/profil_edition
    defaults: { _controller: sitebdeParrainageBundle:Parrainage:profilEdition }

sitebde_parrainage_demande_parrainage:
    path:     /parrainage/page_a_supprimer-{idEtudiant}
    defaults: { _controller: sitebdeParrainageBundle:Parrainage:demandeParrainage }
