<?php

namespace sitebde\SiteVitrineBundle\Repository;

/**
 * InformationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InformationRepository extends \Doctrine\ORM\EntityRepository
{
    // Retourne toutes les informations par ordre alphabétique
    public function getInformationsTriees()
    {
        // Récupérer le gestionnaire d'entités
        $gestionnaireEntites = $this->_em;
        
        // Ecriture de la requête personnalisée
        $requetePerso = $gestionnaireEntites->createQuery('SELECT i
                                                          FROM sitebdeSiteVitrineBundle:Information i
                                                          ORDER BY i.titre');
        
        // Retourner les résultats de l'exécution de la requête
        return $requetePerso->getResult();
    }
}
