<?php

namespace sitebde\SiteVitrineBundle\Repository;

/**
 * TestSuperMappedClassRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestSuperMappedClassRepository extends \Doctrine\ORM\EntityRepository
{
}
