<?php

namespace sitebde\SiteVitrineBundle\Repository;

/**
 * TestSubMappedClassRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestSubMappedClassRepository extends \Doctrine\ORM\EntityRepository
{
}
