sitebde_siteVitrine_accueil:
    path: /
    defaults: { _controller: sitebdeSiteVitrineBundle:SiteVitrine:accueil }

sitebde_siteVitrine_listeActualites:
    path: /actualites
    defaults: { _controller: sitebdeSiteVitrineBundle:SiteVitrine:listeActualites }

sitebde_siteVitrine_detailsActualite:
    path: /actualites/{idActu}
    defaults: { _controller: sitebdeSiteVitrineBundle:SiteVitrine:detailsActualite }

sitebde_siteVitrine_listeEvenements:
    path: /evenements
    defaults: { _controller: sitebdeSiteVitrineBundle:SiteVitrine:listeEvenements }
    
sitebde_siteVitrine_detailsEvenement:
    path: /evenements/{idEvent}
    defaults: { _controller: sitebdeSiteVitrineBundle:SiteVitrine:detailsEvenement }
    
sitebde_siteVitrine_information:
    path: /informations/{idInfo}
    defaults: { _controller: sitebdeSiteVitrineBundle:SiteVitrine:information }

sitebde_siteVitrine_connexion:
    path: /connexion
    defaults: { _controller: sitebdeSiteVitrineBundle:SiteVitrine:connexion }
    
sitebde_siteVitrine_ajouterActualite:
    path: /ajouterActualite
    defaults: { _controller: sitebdeSiteVitrineBundle:SiteVitrine:ajouterActualite }
    
sitebde_siteVitrine_ajouterEvenement:
    path: /ajouterEvenement
    defaults: { _controller: sitebdeSiteVitrineBundle:SiteVitrine:ajouterEvenement }
    
sitebde_siteVitrine_modifierActualite:
    path: /modifierActualite/{id}
    defaults: { _controller: sitebdeSiteVitrineBundle:SiteVitrine:modifierActualite }
    
sitebde_siteVitrine_modifierEvenement:
    path: /modifierEvenement/{id}
    defaults: { _controller: sitebdeSiteVitrineBundle:SiteVitrine:modifierEvenement }
    
sitebde_siteVitrine_modifierInformation:
    path: /modifierInformation/{id}
    defaults: { _controller: sitebdeSiteVitrineBundle:SiteVitrine:modifierInformation }