# ##############################################
# ############## Partie Visiteurs ##############
# ##############################################
mentions_legales_site_vitrine:
    path: /mentionsLegalesVisiteurs
    defaults: { _controller: sitebdeSiteVitrineBundle:SiteVitrine:mentionsLegales }

sitebde_siteVitrine_accueil:
    path: /
    defaults: { _controller: sitebdeSiteVitrineBundle:SiteVitrine:accueil }

sitebde_siteVitrine_liste_actualites:
    path: /actualites
    defaults: { _controller: sitebdeSiteVitrineBundle:SiteVitrine:listeActualites }

sitebde_siteVitrine_details_actualite:
    path: /actualites/{idActu}
    defaults: { _controller: sitebdeSiteVitrineBundle:SiteVitrine:detailsActualite }

sitebde_siteVitrine_liste_evenements:
    path: /evenements
    defaults: { _controller: sitebdeSiteVitrineBundle:SiteVitrine:listeEvenements }
    
sitebde_siteVitrine_details_evenement:
    path: /evenements/{idEvent}
    defaults: { _controller: sitebdeSiteVitrineBundle:SiteVitrine:detailsEvenement }

sitebde_siteVitrine_information:
    path: /informations/{idInfo}
    defaults: { _controller: sitebdeSiteVitrineBundle:SiteVitrine:information }

sitebde_siteVitrine_liste_informations:
    path: /informations
    defaults: { _controller: sitebdeSiteVitrineBundle:SiteVitrine:listeInformations }


# ##############################################
# ################# Partie BDE #################
# ##############################################
    
    
sitebde_siteVitrine_ajouter_actualite:
    path: /admin/ajouterActualite
    defaults: { _controller: sitebdeSiteVitrineBundle:SiteVitrine:ajouterActualite }
    
sitebde_siteVitrine_ajouter_evenement:
    path: /admin/ajouterEvenement
    defaults: { _controller: sitebdeSiteVitrineBundle:SiteVitrine:ajouterEvenement }

sitebde_siteVitrine_ajouter_information:
    path: /admin/ajouterInformation
    defaults: { _controller: sitebdeSiteVitrineBundle:SiteVitrine:ajouterInformation }
    
sitebde_siteVitrine_modifier_actualite:
    path: /admin/modifierActualite/{idActu}
    defaults: { _controller: sitebdeSiteVitrineBundle:SiteVitrine:modifierActualite }
    
sitebde_siteVitrine_modifier_evenement:
    path: /admin/modifierEvenement/{idEvent}
    defaults: { _controller: sitebdeSiteVitrineBundle:SiteVitrine:modifierEvenement }
    
sitebde_siteVitrine_modifier_information:
    path: /admin/modifierInformation/{idInfo}
    defaults: { _controller: sitebdeSiteVitrineBundle:SiteVitrine:modifierInformation }

sitebde_siteVitrine_supprimer_actualite:
    path: /admin/supprimerActualite/{idActu}
    defaults: { _controller: sitebdeSiteVitrineBundle:SiteVitrine:supprimerActualite }

sitebde_siteVitrine_supprimer_evenement:
    path: /admin/supprimerEvenement/{idEvent}
    defaults: { _controller: sitebdeSiteVitrineBundle:SiteVitrine:supprimerEvenement }
    
sitebde_siteVitrine_supprimer_information:
    path: /admin/supprimerInformation/{idInfo}
    defaults: { _controller: sitebdeSiteVitrineBundle:SiteVitrine:supprimerInformation }
    
    
# ##############################################
# ################ Partie Admin ################
# ##############################################


sitebde_siteVitrine_page_admin:
    path: /admin/page_admin
    defaults: { _controller: sitebdeSiteVitrineBundle:SiteVitrine:pageAdmin }
    
sitebde_siteVitrine_actualiser_etudiants_bd:
    path: /admin/actualiser_etudiants_bd
    defaults: { _controller: sitebdeSiteVitrineBundle:SiteVitrine:actualiserEtudiantsBD }
    
sitebde_siteVitrine_gerer_droits_etudiants:
    path: /admin/gerer_droits_etudiants
    defaults: { _controller: sitebdeSiteVitrineBundle:SiteVitrine:gererDroitsEtudiants }
    
sitebde_siteVitrine_parrainage_automatique:
    path: /admin/parrainage_automatique
    defaults: { _controller: sitebdeSiteVitrineBundle:SiteVitrine:associationsAutomatique }
    
supprimer_evenements_par_date:
    path: /admin/supprimer_evenements_par_date
    defaults: { _controller: sitebdeSiteVitrineBundle:SiteVitrine:supprimerEvenementsParDate }
    
supprimer_actualites_par_date:
    path: /admin/supprimer_actualites_par_date
    defaults: { _controller: sitebdeSiteVitrineBundle:SiteVitrine:supprimerActualitesParDate }
    
supprimer_informations_par_date:
    path: /admin/supprimer_informations_par_date
    defaults: { _controller: sitebdeSiteVitrineBundle:SiteVitrine:supprimerInformationsParDate }