connexion:
    path:     /connexion
    defaults: { _controller: sitebdeSecuriteBundle:Securite:connexion }
    
verif_connexion:
    path:     /verif-connexion
    
verif_connexion_perso:
    path:     /verif-connexion-perso
    defaults: { _controller: sitebdeSecuriteBundle:Securite:verifConnexionPerso }
    methods:  [POST]
    
deconnexion:
    path: /deconnexion
    
    
    
deconnexion_perso:
    path: /deconnexion-perso
    defaults: { _controller: sitebdeSecuriteBundle:Securite:deconnexionPerso }
