<?php

namespace sitebde\ParrainageBundle\Repository;

/**
 * DemandeParrainageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeParrainageRepository extends \Doctrine\ORM\EntityRepository
{
}
