<?php

namespace sitebde\ParrainageBundle\Repository;

/**
 * DemandeParrainageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeParrainageRepository extends \Doctrine\ORM\EntityRepository
{
    public function getDemandesNonValidees()
    {
         // Récupérer le gestionnaire d'entités
        $gestionnaireEntites = $this->_em;
        
        // Ecriture de la requête personnalisée
        $requetePerso = $gestionnaireEntites->createQuery('SELECT d
                                                          FROM sitebdeParrainageBundle:DemandeParrainage d
                                                          WHERE d.estAcceptee = 0');
        
        // Retourner les résultats de l'exécution de la requête
        return $requetePerso->getResult();
    }
}
