<?php

namespace sitebde\ParrainageBundle\Repository;

/**
 * EtudiantLoisirRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtudiantLoisirRepository extends \Doctrine\ORM\EntityRepository
{
}
