<?php

namespace sitebde\ParrainageBundle\Repository;

/**
 * EtudiantSportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtudiantSportRepository extends \Doctrine\ORM\EntityRepository
{
}
