<?php

namespace sitebde\ParrainageBundle\Repository;

/**
 * EtudiantMatiereForteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtudiantMatiereForteRepository extends \Doctrine\ORM\EntityRepository
{
}
