<?php

namespace sitebde\ParrainageBundle\Repository;

/**
 * EtudiantMatiereFaibleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtudiantMatiereFaibleRepository extends \Doctrine\ORM\EntityRepository
{
    public function getEtudiantMatiereFaibleParEtudiant($idEtudiant)
    {
        // Récupérer le gestionnaire d'entités
        $gestionnaireEntites = $this->_em;
        
        // Ecriture de la requête personnalisée
        $requetePerso = $gestionnaireEntites->createQuery('SELECT emfb
                                                          FROM sitebdeParrainageBundle:EtudiantMatiereFaible emfb
                                                          WHERE emfb.etudiant = :idEtudiant');
        
        $requetePerso->setParameter('idEtudiant', $idEtudiant);
        
        // Retourner les résultats de l'exécution de la requête
        return $requetePerso->getResult();
    }
}
