<?php

namespace sitebde\ParrainageBundle\Repository;

/**
 * EtudiantMatiereFaibleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtudiantMatiereFaibleRepository extends \Doctrine\ORM\EntityRepository
{
}
