<?php

namespace sitebde\ParrainageBundle\Repository;

/**
 * EtudiantMatiereForteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtudiantMatiereForteRepository extends \Doctrine\ORM\EntityRepository
{
    public function getEtudiantMatiereFortesParEtudiant($idEtudiant)
    {
        // Récupérer le gestionnaire d'entités
        $gestionnaireEntites = $this->_em;
        
        // Ecriture de la requête personnalisée
        $requetePerso = $gestionnaireEntites->createQuery('SELECT emft
                                                          FROM sitebdeParrainageBundle:EtudiantMatiereForte emft
                                                          WHERE emft.etudiant = :idEtudiant');
        
        $requetePerso->setParameter('idEtudiant', $idEtudiant);
        
        // Retourner les résultats de l'exécution de la requête
        return $requetePerso->getResult();
    }
}
