<?php

namespace sitebde\ParrainageBundle\Repository;

/**
 * MatiereForteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatiereForteRepository extends \Doctrine\ORM\EntityRepository
{
}
