<?php

namespace sitebde\ParrainageBundle\Repository;

/**
 * MatiereFaibleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatiereFaibleRepository extends \Doctrine\ORM\EntityRepository
{
}
